### ISSUE TITLE
How do I run this on non-Android?

### ISSUE THREAD

**Issue by fishface60** [JasonMahdjoub/UPnPIGD#2]
The README.md listing separate config for if you need to run with Android implies that it can be run without Android.

I ported some code that previously used jupnp over to this and I got this error.

```
Exception in thread "Thread-13" java.lang.ExceptionInInitializerError
        at com.distrimind.upnp_igd.DefaultUpnpServiceConfiguration.getTransportConfiguration(DefaultUpnpServiceConfiguration.java:170)
        at com.distrimind.upnp_igd.DefaultUpnpServiceConfiguration.createStreamServer(DefaultUpnpServiceConfiguration.java:191)
        at com.distrimind.upnp_igd.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:461)
        at com.distrimind.upnp_igd.transport.RouterImpl.enable(RouterImpl.java:134)
        at com.distrimind.upnp_igd.UpnpServiceImpl.<init>(UpnpServiceImpl.java:88)
        at ...
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Please add dependency com.distrimind.upnp_igd.android:UPnPIGD-Android
        at com.distrimind.upnp_igd.transport.TransportConfigurationProvider.<clinit>(TransportConfigurationProvider.java:38)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: com.distrimind.upnp_igd.android.transport.JettyTransportConfiguration
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:421)
        at java.base/java.lang.Class.forName(Class.java:412)
        at com.distrimind.upnp_igd.transport.TransportConfigurationProvider.<clinit>(TransportConfigurationProvider.java:36)
        ... 11 more
```

jupnp had a jetty-based transport implementation that was used in the default configuration, is there some other way I need to create my `UpnpService`  to use a different implementation?

**Comment by JasonMahdjoub** [comment]
Yes. I a new to maintaining this code. I was thinking that if the tests are working, all was OK. I have no time to test this code directly into a project. I have sorry for the lack of test. I will make modifications soon to make the code working.

**Comment by JasonMahdjoub** [comment]
You can now import version 1.2.0-BETA. It should work; however, the Android version does not compile, which is why the project is currently marked as "build: failed." I will run more tests in the coming weeks to make it more stable.
